name: Release, Build and Deploy

on:
    push:
        tags:
            - v[0-9]+.[0-9]+.[0-9]+*

permissions:
    contents: write

concurrency:
    group: ${{ github.ref }}-${{ github.workflow }}
    cancel-in-progress: true

jobs:
    create-release:
        name: Create GitHub Release
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Branch
              uses: actions/checkout@v4
            - name: Create GitHub Release
              uses: taiki-e/create-gh-release-action@v1
              with:
                  changelog: CHANGELOG.md
                  token: ${{ secrets.GITHUB_TOKEN }}

    build-deploy:
        name: Build Website and Deploy to GitHub Pages
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Branch
              uses: actions/checkout@v4
            - name: Setup Node.js Environment
              uses: actions/setup-node@v4
              with:
                  node-version: 22
                  cache: npm
            - name: Install Dependencies
              run: npm ci
            - name: Bundle Extensions
              run: npm run build
            - name: Deploy to GitHub Pages
              uses: peaceiris/actions-gh-pages@v4
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  publish_dir: src/.vitepress/dist
